corrected for error.
corrected for error

Common problem when copying from broad wdl blogs (they have paranthesis missing for input)

ERROR: Unexpected symbol (line 46, col 5) when parsing 'setter'.

Expected equal, got "String".

    String queue_name
    ^

$setter = :equal $e -> $1